# Generated by Django 2.2.5 on 2019-09-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20190922_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Самовивіз', 'Самовивіз'), ('Доставка', 'Доставка')], default='Самовивіз', max_length=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Cart', verbose_name='Товари'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обробляється', 'Обробляється'), ('Виконується', 'Виконується'), ('Оплачено', 'Оплачено')], default='Обробляється', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Ціна'),
        ),
    ]
