# Generated by Django 2.2.5 on 2019-09-26 07:31

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20190926_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='Xiaomi', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Brand', verbose_name='Виробник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Смартфони', on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Category', verbose_name='Категорія'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.models.get_image_folder, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
