# Generated by Django 2.2.5 on 2019-09-26 07:50

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20190926_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=ecommerce.models.get_image_folder, verbose_name='Фото'),
        ),
    ]
