# Generated by Django 2.2.5 on 2019-09-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20190926_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обробляється', 'Обробляється'), ('Виконується', 'Виконується'), ('Оплачено', 'Оплачено'), ('Відхилено', 'Відхилено')], default='Обробляється', max_length=100),
        ),
    ]
